# Generated by Django 3.0.7 on 2020-07-13 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Genre'),
        ),
    ]
